---
development:
  cloud_name: <%= Credential.fetch(:cloudinary, :cloud_name) %>
  api_key: <%= Credential.fetch(:cloudinary, :api_key) %>
  api_secret: <%= Credential.fetch(:cloudinary, :api_secret) %>
  enhance_image_tag: true
  static_file_support: false

test:
  cloud_name: <%= Credential.fetch(:cloudinary, :cloud_name) %>
  api_key: <%= Credential.fetch(:cloudinary, :api_key) %>
  api_secret: <%= Credential.fetch(:cloudinary, :api_secret) %>
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: <%= Credential.fetch(:cloudinary, :cloud_name) %>
  api_key: <%= Credential.fetch(:cloudinary, :api_key) %>
  api_secret: <%= Credential.fetch(:cloudinary, :api_secret) %>
  enhance_image_tag: true
  static_file_support: true
